<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Conductor_transporte_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get conductor_transporte by id
     */
    function get_conductor_transporte($id)
    {
        return $this->db->get_where('conductor_transporte',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all conductor_transporte
     */
    function get_all_conductor_transporte()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('conductor_transporte')->result_array();
    }
        
    /*
     * function to add new conductor_transporte
     */
    function add_conductor_transporte($params)
    {
        $this->db->insert('conductor_transporte',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update conductor_transporte
     */
    function update_conductor_transporte($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('conductor_transporte',$params);
    }
    
    /*
     * function to delete conductor_transporte
     */
    function delete_conductor_transporte($id)
    {
        return $this->db->delete('conductor_transporte',array('id'=>$id));
    }
}
