<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Persona_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get persona by id
     */
    function get_persona($id)
    {
        return $this->db->get_where('persona',array('id'=>$id))->row_array();
    }

    function get_persona_by_identificacion($identificacion){
      return $this->db->get_where('persona',array('identificacion'=>$identificacion))->row_array();
    }

    function get_persona_by_number($telefono){
      $this->db->select('pe.*, pp.nombre as nombre_tipo_perfil');
      $this->db->from('persona pe, persona_perfil pp');
      $this->db->where("pe.persona_perfil_id = pp.id AND pe.telefono = {$telefono}");
      return $this->db->get()->row_array();
    }

    /*
     * Get all persona
     */
    function get_all_persona()
    {
        $this->db->select('pe.id as id, pe.nombres as nombres, pe.apellido_paterno as apellido_paterno, pe.apellido_materno as apellido_materno, pe.identificacion as identificacion, pe.saldo_disponible as saldo_disponible, pe.telefono as telefono, pe.estado as estado, pp.nombre as perfil_nombre');
        $this->db->from('persona pe,  persona_perfil pp');
        $this->db->where('pe.persona_perfil_id = pp.id');
        $this->db->order_by('pe.id', 'desc');
        return $this->db->get()->result_array();

    }

    /*
     * function to add new persona
     */
    function add_persona($params)
    {
        $this->db->insert('persona',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update persona
     */
    function update_persona($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('persona',$params);
    }

    /*
     * function to delete persona
     */
    function delete_persona($id)
    {
        return $this->db->delete('persona',array('id'=>$id));
    }
}
