<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Persona_viaje_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get persona_viaje by id
     */
    function get_persona_viaje($id)
    {
        return $this->db->get_where('persona_viaje',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all persona_viaje
     */
    function get_all_persona_viaje()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('persona_viaje')->result_array();
    }
        
    /*
     * function to add new persona_viaje
     */
    function add_persona_viaje($params)
    {
        $this->db->insert('persona_viaje',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update persona_viaje
     */
    function update_persona_viaje($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('persona_viaje',$params);
    }
    
    /*
     * function to delete persona_viaje
     */
    function delete_persona_viaje($id)
    {
        return $this->db->delete('persona_viaje',array('id'=>$id));
    }
}
