<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Persona_perfil_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get persona_perfil by id
     */
    function get_persona_perfil($id)
    {
        return $this->db->get_where('persona_perfil',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all persona_perfil
     */
    function get_all_persona_perfil()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('persona_perfil')->result_array();
    }
        
    /*
     * function to add new persona_perfil
     */
    function add_persona_perfil($params)
    {
        $this->db->insert('persona_perfil',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update persona_perfil
     */
    function update_persona_perfil($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('persona_perfil',$params);
    }
    
    /*
     * function to delete persona_perfil
     */
    function delete_persona_perfil($id)
    {
        return $this->db->delete('persona_perfil',array('id'=>$id));
    }
}
