<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Rutum_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get rutum by id
     */
    function get_rutum($id)
    {
        return $this->db->get_where('ruta',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all ruta
     */
    function get_all_ruta()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('ruta')->result_array();
    }
        
    /*
     * function to add new rutum
     */
    function add_rutum($params)
    {
        $this->db->insert('ruta',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update rutum
     */
    function update_rutum($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('ruta',$params);
    }
    
    /*
     * function to delete rutum
     */
    function delete_rutum($id)
    {
        return $this->db->delete('ruta',array('id'=>$id));
    }
}
