<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Tipo_alertum_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get tipo_alertum by id
     */
    function get_tipo_alertum($id)
    {
        return $this->db->get_where('tipo_alerta',array('id'=>$id))->row_array();
    }

    /*
     * Get all tipo_alerta
     */
    function get_all_tipo_alerta()
    {
        $this->db->order_by('id', 'asc');
        return $this->db->get('tipo_alerta')->result_array();
    }

    /*
     * function to add new tipo_alertum
     */
    function add_tipo_alertum($params)
    {
        $this->db->insert('tipo_alerta',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update tipo_alertum
     */
    function update_tipo_alertum($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tipo_alerta',$params);
    }

    /*
     * function to delete tipo_alertum
     */
    function delete_tipo_alertum($id)
    {
        return $this->db->delete('tipo_alerta',array('id'=>$id));
    }
}
