<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipo_transporte_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tipo_transporte by id
     */
    function get_tipo_transporte($id)
    {
        return $this->db->get_where('tipo_transporte',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tipo_transporte
     */
    function get_all_tipo_transporte()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('tipo_transporte')->result_array();
    }
        
    /*
     * function to add new tipo_transporte
     */
    function add_tipo_transporte($params)
    {
        $this->db->insert('tipo_transporte',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tipo_transporte
     */
    function update_tipo_transporte($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tipo_transporte',$params);
    }
    
    /*
     * function to delete tipo_transporte
     */
    function delete_tipo_transporte($id)
    {
        return $this->db->delete('tipo_transporte',array('id'=>$id));
    }
}
