<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Persona_perfil extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Persona_perfil_model');
    }

    /*
     * Listing of persona_perfil
     */
    function index()
    {
        $data['persona_perfil'] = $this->Persona_perfil_model->get_all_persona_perfil();

        $data['_view'] = 'persona_perfil/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new persona_perfil
     */
    function add()
    {
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nombre','Nombre','required|max_length[30]|is_unique[persona_perfil.nombre]',
    array('required' => 'Debe agregar un nombre para el tipo de perfil de persona.',
          'max_length' => 'Como máximo solo pueden ser 30 caracteres.',
          'is_unique' => 'Este nombre ya ha sido registrado anteriormente.'
        )
  );

		if($this->form_validation->run())
        {
            $params = array(
				       'nombre' => strtoupper($this->input->post('nombre'))
            );

            $persona_perfil_id = $this->Persona_perfil_model->add_persona_perfil($params);
            redirect('persona_perfil/index');
        }
        else
        {
            $data['_view'] = 'persona_perfil/add';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Editing a persona_perfil
     */
    function edit($id)
    {
        // check if the persona_perfil exists before trying to edit it
        $data['persona_perfil'] = $this->Persona_perfil_model->get_persona_perfil($id);

        if(isset($data['persona_perfil']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nombre','Nombre','required|max_length[30]|edit_unique[persona_perfil.nombre.'.$id.']',
      array('required' => 'Debe agregar un nombre para el tipo de perfil de persona.',
            'max_length' => 'Como máximo solo pueden ser 30 caracteres.',
            'edit_unique' => 'Este nombre ya ha sido registrado anteriormente.'
          )
    );

			if($this->form_validation->run())
            {
                $params = array(
					'nombre' => $this->input->post('nombre')
                );

                $this->Persona_perfil_model->update_persona_perfil($id,$params);
                redirect('persona_perfil/index');
            }
            else
            {
                $data['_view'] = 'persona_perfil/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The persona_perfil you are trying to edit does not exist.');
    }

    /*
     * Deleting persona_perfil
     */
    function remove($id)
    {
        $persona_perfil = $this->Persona_perfil_model->get_persona_perfil($id);

        // check if the persona_perfil exists before trying to delete it
        if(isset($persona_perfil['id']))
        {
            $this->Persona_perfil_model->delete_persona_perfil($id);
            redirect('persona_perfil/index');
        }
        else
            show_error('The persona_perfil you are trying to delete does not exist.');
    }

    function deshabilitar($id){
      $data['persona_perfil'] = $this->Persona_perfil_model->get_persona_perfil($id);

      if(isset($data['persona_perfil']['id'])){
        $params = array('estado' => 0);
        $this->Persona_perfil_model->update_persona_perfil($id,$params);
        redirect('persona_perfil/index');
      }else{
        show_error('El perfil de persona que intenta deshabilitar no existe.');
      }

    }
    function habilitar($id){
      $data['persona_perfil'] = $this->Persona_perfil_model->get_persona_perfil($id);

      if(isset($data['persona_perfil']['id'])){
        $params = array('estado' => 1);
        $this->Persona_perfil_model->update_persona_perfil($id,$params);
        redirect('persona_perfil/index');
      }else{
        show_error('El perfil de persona que intenta habilitar no existe.');
      }
    }


}
