<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Persona_perfil extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Persona_perfil_model');
    } 

    /*
     * Listing of persona_perfil
     */
    function index()
    {
        $data['persona_perfil'] = $this->Persona_perfil_model->get_all_persona_perfil();
        
        $data['_view'] = 'persona_perfil/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new persona_perfil
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nombre','Nombre','required|max_length[30]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nombre' => $this->input->post('nombre'),
				'estado' => $this->input->post('estado'),
            );
            
            $persona_perfil_id = $this->Persona_perfil_model->add_persona_perfil($params);
            redirect('persona_perfil/index');
        }
        else
        {            
            $data['_view'] = 'persona_perfil/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a persona_perfil
     */
    function edit($id)
    {   
        // check if the persona_perfil exists before trying to edit it
        $data['persona_perfil'] = $this->Persona_perfil_model->get_persona_perfil($id);
        
        if(isset($data['persona_perfil']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nombre','Nombre','required|max_length[30]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nombre' => $this->input->post('nombre'),
					'estado' => $this->input->post('estado'),
                );

                $this->Persona_perfil_model->update_persona_perfil($id,$params);            
                redirect('persona_perfil/index');
            }
            else
            {
                $data['_view'] = 'persona_perfil/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The persona_perfil you are trying to edit does not exist.');
    } 

    /*
     * Deleting persona_perfil
     */
    function remove($id)
    {
        $persona_perfil = $this->Persona_perfil_model->get_persona_perfil($id);

        // check if the persona_perfil exists before trying to delete it
        if(isset($persona_perfil['id']))
        {
            $this->Persona_perfil_model->delete_persona_perfil($id);
            redirect('persona_perfil/index');
        }
        else
            show_error('The persona_perfil you are trying to delete does not exist.');
    }
    
}
