<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Tipo_transporte extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tipo_transporte_model');
    }

    /*
     * Listing of tipo_transporte
     */
    function index()
    {
        $data['tipo_transporte'] = $this->Tipo_transporte_model->get_all_tipo_transporte();

        $data['_view'] = 'tipo_transporte/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tipo_transporte
     */
    function add()
    {
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nombre','Nombre','required|max_length[30]|is_unique[tipo_transporte.nombre]',
      array('required' => 'Debe agregar un nombre para el tipo de transporte.',
            'max_length' => 'Como máximo solo pueden ser 30 caracteres.',
            'is_unique' => 'Este nombre ya ha sido registrado anteriormente.'
          )
    );

		if($this->form_validation->run())
        {
            $params = array(
				'nombre' => $this->input->post('nombre'),
				'estado' => 1,
            );

            $tipo_transporte_id = $this->Tipo_transporte_model->add_tipo_transporte($params);
            redirect('tipo_transporte/index');
        }
        else
        {
            $data['_view'] = 'tipo_transporte/add';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Editing a tipo_transporte
     */
    function edit($id)
    {
        // check if the tipo_transporte exists before trying to edit it
        $data['tipo_transporte'] = $this->Tipo_transporte_model->get_tipo_transporte($id);

        if(isset($data['tipo_transporte']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nombre','Nombre','required|max_length[30]|edit_unique[tipo_transporte.nombre.'.$id.']',
      array('required' => 'Debe agregar un nombre para el tipo de transporte.',
            'max_length' => 'Como máximo solo pueden ser 30 caracteres.',
            'edit_unique' => 'Este nombre ya ha sido registrado anteriormente.'
        )
    );

			if($this->form_validation->run())
            {
                $params = array(
					               'nombre' => $this->input->post('nombre')
                );

                $this->Tipo_transporte_model->update_tipo_transporte($id,$params);
                redirect('tipo_transporte/index');
            }
            else
            {
                $data['_view'] = 'tipo_transporte/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tipo_transporte you are trying to edit does not exist.');
    }

    /*
     * Deleting tipo_transporte
     */
    function remove($id)
    {
        $tipo_transporte = $this->Tipo_transporte_model->get_tipo_transporte($id);

        // check if the tipo_transporte exists before trying to delete it
        if(isset($tipo_transporte['id']))
        {
            $this->Tipo_transporte_model->delete_tipo_transporte($id);
            redirect('tipo_transporte/index');
        }
        else
            show_error('The tipo_transporte you are trying to delete does not exist.');
    }

    function deshabilitar($id){
      $data['tipo_transporte'] = $this->Tipo_transporte_model->get_tipo_transporte($id);

      if(isset($data['tipo_transporte']['id'])){
        $params = array('estado' => 0);
        $this->Tipo_transporte_model->update_tipo_transporte($id,$params);
        redirect('tipo_transporte/index');
      }else{
        show_error('El tipo de transporte que intenta deshabilitar no existe.');
      }

    }
    function habilitar($id){
      $data['tipo_transporte'] = $this->Tipo_transporte_model->get_tipo_transporte($id);

      if(isset($data['tipo_transporte']['id'])){
        $params = array('estado' => 1);
        $this->Tipo_transporte_model->update_tipo_transporte($id,$params);
        redirect('tipo_transporte/index');
      }else{
        show_error('El tipo de transporte que intenta habilitar no existe.');
      }
    }

}
