<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Tipo_alertum extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tipo_alertum_model');
    }

    /*
     * Listing of tipo_alerta
     */
    function index()
    {
        $data['tipo_alerta'] = $this->Tipo_alertum_model->get_all_tipo_alerta();

        $data['_view'] = 'tipo_alertum/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tipo_alertum
     */
    function add()
    {
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nombre','Nombre','required|max_length[45]|is_unique[tipo_alerta.nombre]',
    array('required' => 'Debe agregar un nombre para el tipo de alerta.',
          'max_length' => 'Como máximo solo pueden ser 45 caracteres.',
          'is_unique' => 'Nombre ya ha sido registrado anteriormente'
        )
  );

		if($this->form_validation->run())
        {
            $params = array(
				'nombre' => $this->input->post('nombre'),
				'estado' => 1,
            );

            $tipo_alertum_id = $this->Tipo_alertum_model->add_tipo_alertum($params);
            redirect('tipo_alertum/index');
        }
        else
        {
            $data['_view'] = 'tipo_alertum/add';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Editing a tipo_alertum
     */
    function edit($id)
    {
        // check if the tipo_alertum exists before trying to edit it
        $data['tipo_alertum'] = $this->Tipo_alertum_model->get_tipo_alertum($id);

        if(isset($data['tipo_alertum']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nombre','Nombre','required|max_length[45]|edit_unique[tipo_alerta.nombre.'.$id.']',
      array('required' => 'Debe agregar un nombre para el tipo de alerta.',
            'max_length' => 'Como máximo solo pueden ser 45 caracteres.',
            'edit_unique' => 'Nombre ya ha sido registrado anteriormente'
          )
    );

			if($this->form_validation->run())
            {
                $params = array(
					'nombre' => $this->input->post('nombre')
                );

                $this->Tipo_alertum_model->update_tipo_alertum($id,$params);
                redirect('tipo_alertum/index');
            }
            else
            {
                $data['_view'] = 'tipo_alertum/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tipo_alertum you are trying to edit does not exist.');
    }

    /*
     * Deleting tipo_alertum
     */
    function remove($id)
    {
        $tipo_alertum = $this->Tipo_alertum_model->get_tipo_alertum($id);

        // check if the tipo_alertum exists before trying to delete it
        if(isset($tipo_alertum['id']))
        {
            $this->Tipo_alertum_model->delete_tipo_alertum($id);
            redirect('tipo_alertum/index');
        }
        else
            show_error('The tipo_alertum you are trying to delete does not exist.');
    }

    function deshabilitar($id){
      $data['tipo_alertum'] = $this->Tipo_alertum_model->get_tipo_alertum($id);

      if(isset($data['tipo_alertum']['id'])){
        $params = array('estado' => 0);
        $this->Tipo_alertum_model->update_tipo_alertum($id,$params);
        redirect('tipo_alertum/index');
      }else{
        show_error('El tipo de alerta que intenta deshabilitar no existe.');
      }

    }
    function habilitar($id){
      $data['tipo_alertum'] = $this->Tipo_alertum_model->get_tipo_alertum($id);

      if(isset($data['tipo_alertum']['id'])){
        $params = array('estado' => 1);
        $this->Tipo_alertum_model->update_tipo_alertum($id,$params);
        redirect('tipo_alertum/index');
      }else{
        show_error('El tipo de alerta que intenta habilitar no existe.');
      }
    }

}
