<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Transporte_unidad extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Transporte_unidad_model');
    } 

    /*
     * Listing of transporte_unidad
     */
    function index()
    {
        $data['transporte_unidad'] = $this->Transporte_unidad_model->get_all_transporte_unidad();
        
        $data['_view'] = 'transporte_unidad/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new transporte_unidad
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('tipo_transporte_id','Tipo Transporte Id','required');
		$this->form_validation->set_rules('identificacion','Identificacion','required|max_length[7]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'tipo_transporte_id' => $this->input->post('tipo_transporte_id'),
				'identificacion' => $this->input->post('identificacion'),
				'estado' => $this->input->post('estado'),
            );
            
            $transporte_unidad_id = $this->Transporte_unidad_model->add_transporte_unidad($params);
            redirect('transporte_unidad/index');
        }
        else
        {
			$this->load->model('Tipo_transporte_model');
			$data['all_tipo_transporte'] = $this->Tipo_transporte_model->get_all_tipo_transporte();
            
            $data['_view'] = 'transporte_unidad/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a transporte_unidad
     */
    function edit($id)
    {   
        // check if the transporte_unidad exists before trying to edit it
        $data['transporte_unidad'] = $this->Transporte_unidad_model->get_transporte_unidad($id);
        
        if(isset($data['transporte_unidad']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('tipo_transporte_id','Tipo Transporte Id','required');
			$this->form_validation->set_rules('identificacion','Identificacion','required|max_length[7]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'tipo_transporte_id' => $this->input->post('tipo_transporte_id'),
					'identificacion' => $this->input->post('identificacion'),
					'estado' => $this->input->post('estado'),
                );

                $this->Transporte_unidad_model->update_transporte_unidad($id,$params);            
                redirect('transporte_unidad/index');
            }
            else
            {
				$this->load->model('Tipo_transporte_model');
				$data['all_tipo_transporte'] = $this->Tipo_transporte_model->get_all_tipo_transporte();

                $data['_view'] = 'transporte_unidad/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The transporte_unidad you are trying to edit does not exist.');
    } 

    /*
     * Deleting transporte_unidad
     */
    function remove($id)
    {
        $transporte_unidad = $this->Transporte_unidad_model->get_transporte_unidad($id);

        // check if the transporte_unidad exists before trying to delete it
        if(isset($transporte_unidad['id']))
        {
            $this->Transporte_unidad_model->delete_transporte_unidad($id);
            redirect('transporte_unidad/index');
        }
        else
            show_error('The transporte_unidad you are trying to delete does not exist.');
    }
    
}
