<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Usuario extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Usuario_model');
    }

    /*
     * Listing of usuario
     */
    function index()
    {
        $data['usuario'] = $this->Usuario_model->get_all_usuario();

        $data['_view'] = 'usuario/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new usuario
     */
    function add()
    {
        $this->load->library('form_validation');

		$this->form_validation->set_rules('persona_id','Persona Id','required|max_length[11]',
    array('required' => 'Debe seleccionar una persona para el usuario.',
          'max_length' => 'Como máximo solo pueden ser 11 caracteres.'
        )
  );
		$this->form_validation->set_rules('password','Password','required',
    array('required' => 'Debe ingresar una contraseña para el usuario.'
        )
  );
		$this->form_validation->set_rules('tipo_usuario_id','Tipo Usuario Id','required|max_length[2]',
    array('required' => 'Debe seleccionar un tipo de usuario para el usuario.',
          'max_length' => 'Como máximo solo pueden ser 2 caracteres.'
        )
  );
		$this->form_validation->set_rules('usuario','Usuario','required|max_length[45]|is_unique[usuario.usuario]',
    array('required' => 'Debe escribir un usuario para el usuario.',
          'max_length' => 'Como máximo solo pueden ser 45 caracteres.',
          'is_unique' => 'Este usuario ya ha sido registrado anteriormente',
        )
  );
		$this->form_validation->set_rules('email','Email','required|max_length[50]|valid_email|is_unique[usuario.email]',
    array('required' => 'Debe escribir un correo para el usuario.',
          'max_length' => 'Como máximo solo pueden ser 50 caracteres.',
          'valid_email' => 'Debe ingresar un correo válido',
          'is_unique' => 'Este correo ya ha sido registrado anteriormente',
        )
  );

		if($this->form_validation->run())
        {
            $params = array(
				'persona_id' => $this->input->post('persona_id'),
				'tipo_usuario_id' => $this->input->post('tipo_usuario_id'),
				'password' => $this->input->post('password'),
				'usuario' => $this->input->post('usuario'),
				'email' => $this->input->post('email'),
				'estado' => 1,
            );

            $usuario_id = $this->Usuario_model->add_usuario($params);
            redirect('usuario/index');
        }
        else
        {
			$this->load->model('Persona_model');
			$data['all_persona'] = $this->Persona_model->get_all_persona();

			$this->load->model('Tipo_usuario_model');
			$data['all_tipo_usuario'] = $this->Tipo_usuario_model->get_all_tipo_usuario();

            $data['_view'] = 'usuario/add';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Editing a usuario
     */
    function edit($id)
    {
        // check if the usuario exists before trying to edit it
        $data['usuario'] = $this->Usuario_model->get_usuario($id);

        if(isset($data['usuario']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('persona_id','Persona Id','required|max_length[11]',
      array('required' => 'Debe seleccionar una persona para el usuario.',
            'max_length' => 'Como máximo solo pueden ser 11 caracteres.'
          )
    );
			$this->form_validation->set_rules('password','Password','required',
      array('required' => 'Debe ingresar una contraseña para el usuario.'
          )
    );
			$this->form_validation->set_rules('tipo_usuario_id','Tipo Usuario Id','required|max_length[2]',
      array('required' => 'Debe seleccionar un tipo de usuario para el usuario.',
            'max_length' => 'Como máximo solo pueden ser 2 caracteres.'
          )
    );
			$this->form_validation->set_rules('usuario','Usuario','required|max_length[45]|edit_unique[usuario.usuario.'.$id.']',
      array('required' => 'Debe escribir un usuario para el usuario.',
            'max_length' => 'Como máximo solo pueden ser 45 caracteres.',
            'edit_unique' => 'Este usuario ya ha sido registrado anteriormente',
          )
    );
			$this->form_validation->set_rules('email','Email','required|max_length[50]|valid_email|edit_unique[usuario.email.'.$id.']',
      array('required' => 'Debe escribir un correo para el usuario.',
            'max_length' => 'Como máximo solo pueden ser 50 caracteres.',
            'valid_email' => 'Debe ingresar un correo válido',
            'edit_unique' => 'Este correo ya ha sido registrado anteriormente',
          )
    );



			if($this->form_validation->run())
            {
                $params = array(
					'persona_id' => $this->input->post('persona_id'),
					'tipo_usuario_id' => $this->input->post('tipo_usuario_id'),
					'password' => $this->input->post('password'),
					'usuario' => $this->input->post('usuario'),
					'email' => $this->input->post('email')
                );

                $this->Usuario_model->update_usuario($id,$params);
                redirect('usuario/index');
            }
            else
            {
				$this->load->model('Persona_model');
				$data['all_persona'] = $this->Persona_model->get_all_persona();

				$this->load->model('Tipo_usuario_model');
				$data['all_tipo_usuario'] = $this->Tipo_usuario_model->get_all_tipo_usuario();

                $data['_view'] = 'usuario/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The usuario you are trying to edit does not exist.');
    }

    /*
     * Deleting usuario
     */
    function remove($id)
    {
        $usuario = $this->Usuario_model->get_usuario($id);

        // check if the usuario exists before trying to delete it
        if(isset($usuario['id']))
        {
            $this->Usuario_model->delete_usuario($id);
            redirect('usuario/index');
        }
        else
            show_error('The usuario you are trying to delete does not exist.');
    }



    function deshabilitar($id){
      $data['usuario'] = $this->Usuario_model->get_usuario($id);

      if(isset($data['usuario']['id'])){
        $params = array('estado' => 0);
        $this->Usuario_model->update_usuario($id,$params);
        redirect('usuario/index');
      }else{
        show_error('El usuario que intenta deshabilitar no existe.');
      }

    }
    function habilitar($id){
      $data['usuario'] = $this->Usuario_model->get_usuario($id);

      if(isset($data['usuario']['id'])){
        $params = array('estado' => 1);
        $this->Usuario_model->update_usuario($id,$params);
        redirect('usuario/index');
      }else{
        show_error('El usuario que intenta habilitar no existe.');
      }
    }

}
